### ISSUE TITLE
little improvement?

### ISSUE THREAD

**Issue by victionn** [HyperCoder2975/simple-youtube-api#10]
Just a little thing which I think could be done:

        When playing through a playlist with say a Music bot, when the bot reaches a deleted/private video, it 
        errors with "Error: resource not found" to which, I think could be improved by just gracefully skipping 
        it/bypassing it. Instead of chucking an error which disturbs the whole sequence..

**Comment by appellation** [comment]
you should be able to filter on privacy status based on the new property added in 6ae74d2dcb67d0974bd552875ad00950ab55ff05

**Comment by Abady321x123** [comment]
if you are on master, you can also filter by thumbanils, which private videos and deleted ones don't have! GOOD LUCK.
