### ISSUE TITLE
Requesting Objects

### ISSUE THREAD

**Issue by iamaul** [HyperCoder2975/simple-youtube-api#13]
Would it be cool if you adds some new objects like `likes, dislikes, viewers` for YouTube videos or `subscribers` for YouTube channels, thanks.

**Comment by appellation** [comment]
You should have access to this data through the `raw` property on videos and channels.  However, I'll look at adding some of the more used properties directly to the objects.

**Comment by appellation** [comment]
I'm going to close this, as 5.1.0 added quite a few new properties.
