### ISSUE TITLE
Failed Build Application

### ISSUE THREAD

**Issue by kamalkech** [HyperCoder2975/simple-youtube-api#14]
Failed to minify the code from this file: 
 	./node_modules/simple-youtube-api/src/util.js:1

**Comment by appellation** [comment]
We do not support browser implementations.  If you'd like to support browser usage, you're welcome to make a PR.

**Comment by kamalkech** [comment]
@appellation : 
i already develop an application web react so i must to change "simple-youtube-api" to another package, and i don't know if "We do not support browser implementations" is exist on documentation !!
