### ISSUE TITLE
Question/Feature: Are these features available as I am unable to find them in documentation

### ISSUE THREAD

**Issue by Skillz4Killz** [HyperCoder2975/simple-youtube-api#15]
Good Afternoon,

I am looking for a few things in specific and was unable to find in the documentation.

1. Any way to get info from YouTube Gaming? For example, when someone goes live on stream. How many followers, what game, how many viewers etc
2. A way to get alerts that a user has uploaded a new video on to YouTube.
3. A way to get the list of latest video from a user/channel

Thanking You In Anticipation

**Comment by HyperCoder2975** [comment]
I'm not sure about 1 or 3, but 2 requires a webhook/scraper, which this library doesn't support.

**Comment by Skillz4Killz** [comment]
Thank you!!

I found an alert system with [webhook](https://github.com/3ventic/ytdsc/blob/master/hook.js) but I need somehow to get more information about this video/user/channel. The webhook doesn't provide all the information I would like on this video, user, and channel. Is there any way I can make it so if I get an alert from the webhook to launch

**Comment by SirPacker** [comment]
@Skillz4Killz, Try https://zapier.com/ . They have support for YouTube. A guide for the site can be found [here](https://www.youtube.com/watch?v=bI21mSYhDoo).

**Comment by appellation** [comment]
1. The YouTube livestreaming API is a separate API.  I'm not super excited about the prospect of covering it in this wrapper, as it is essentially a different service.
2. This isn't supported by the YouTube API, as mentioned above.
3. This is already supported by this library by providing additional query options to the `searchVideos` method.  As described on the [YouTube API documentation](https://developers.google.com/youtube/v3/docs/search/list), you can provide `channelId` and `publishedAfter` parameters to limit the search to one channel; if you don't care about a search query, just null it out when making the request.  Example: `youtube.searchVideos(null, 10, { channelId: 'some channel id', publishedAfter: '2018-02-10T00:00:00Z' })`

I will close this issue as none of the 3 things you've addressed pertain to changes in this library as I see it.  You're welcome to continue the conversation if you disagree.
