### ISSUE TITLE
"Error: resource youtube#playlistListResponse not found"

### ISSUE THREAD

**Issue by RealBlackB1RD** [HyperCoder2975/simple-youtube-api#17]
I'm trying to getPlaylist() by a url and its log this error on the console:
"Error: resource youtube#playlistListResponse not found"

I updated the package before.
I check if the error is coming from this package and I tried to see if its coming from this line and  yes I get the error from this line: `const playlist = await youtube.getPlaylist(url);`
url = `string.replace(/<(.+)>/g, '$1');`

**Comment by appellation** [comment]
resource not found indicates that the resource doesn't exist: ie. the YouTube API returned an empty result set. please ensure that your playlist exists and is publicly accessible.

**Comment by RealBlackB1RD** [comment]
There is a way to find if the playlist is private with the package ?

**Comment by appellation** [comment]
i would recommend looking for information regarding authentication in the YouTube API documentation
