### ISSUE TITLE
Requesting private videos

### ISSUE THREAD

**Issue by brandonbothell** [HyperCoder2975/simple-youtube-api#25]
Whenever I try to request videos from a playlist that contains a private video or two, I want to be able to get every video from that playlist except for the private videos, which throw an error. Code example: 

```JavaScript
const playlist = await youtube.getPlaylist(url);
const videos = await playlist.getVideos();
```

The 
```JavaScript
const videos = await playlist.getVideos();
``` 
part causes this error to be thrown when there is a private video in the playlist: 
```JavaScript
Error: resource youtube#videoListResponse not found
```
Is there a way to get past this, or is it not implemented yet?

**Comment by appellation** [comment]
I'm surprised to see that specific error on a `getVideos` call.  If you examine the source, you can see that the `getVideos` method calls the `PlaylistItems` endpoint which I would expect to throw an error related to `youtube#playlistItemResponse` in accordance with the [YouTube documentation](https://developers.google.com/youtube/v3/docs/playlistItems/list#response).  Regardless, having only the code you provided above as context, it does not appear like YouTube supports selectively loading only accessible videos.

**Comment by jasonhaxstuff** [comment]
Here is the full error code if it helps:
```JavaScript
Error: resource youtube#videoListResponse not found
    at make.then.result (C:\Users\SOME NAME\DiscordComTest\node_modules\simple-youtube-api\src\Request.js:35:68)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by jasonhaxstuff** [comment]
Update: I've figured out that it's this code setting off the error:
```JavaScript
const playlist = await youtube.getPlaylist(url);
const videos = await playlist.getVideos();
for (const video of Object.values(videos)) {
	const video2 = await youtube.getVideoByID(video.id);
	await handleVideo(video2, msg, voiceChannel, true);
}
```
The `const video2 = await youtube.getVideoByID(video.id)` part is where `getResource` is being called. If the video is private, it will error. Is there any way to prevent this?
