### ISSUE TITLE
getVideoById();

### ISSUE THREAD

**Issue by NoneIsSome** [HyperCoder2975/simple-youtube-api#29]
I am getting this error when trying to use getVideoById(); This should work, right? It is throwing an error though.

![image](https://user-images.githubusercontent.com/19301186/44312832-4766c580-a3f6-11e8-925e-469fade546d5.png)
![image](https://user-images.githubusercontent.com/19301186/44312829-3453f580-a3f6-11e8-9aa4-dd77664d7243.png)

**Comment by appellation** [comment]
getVideoByID

**Comment by noneissome** [comment]
Woops. That was a bit stupid of me. Sorry.
