### ISSUE TITLE
Some details aren't displaying correctly

### ISSUE THREAD

**Issue by angeloanan** [HyperCoder2975/simple-youtube-api#30]
`Video.maxres` and `Video.durationSeconds` aren't displaying the correct information.

Video.maxres just spews error.
Video.durationSeconds returns with a -1

**Comment by appellation** [comment]
Not all videos have 100% of the data depending on how you got it, so `durationSeconds` returning -1 is not  entirely strange. However, `maxRes` should not be throwing an error.

Can you please be more specific? Which error? Is the video `full`? How did you retrieve the video?

**Comment by angeloanan** [comment]
Not a problem anymore. Sorry for holding back the issue, I forgot this existed.
