### ISSUE TITLE
Search videos with forMine=true - Authentication 

### ISSUE THREAD

**Issue by markm** [HyperCoder2975/simple-youtube-api#39]
Hi, I'm having trouble setting 'forMine' to true in the options. Is there a way for me to use this package to make authenticated calls, such as searching for a list of the authenticated user's videos? Thanks!

**Comment by appellation** [comment]
You'll have to create another instance of `YouTube` with the authorization token you received from the OAuth flow or set the token on a pre-existing instance. The options are passed directly through as URL search parameters, so if the endpoint you're trying to use accepts a `forMine` query parameter, you should be able to simply specify it in the options.

**Comment by markm** [comment]
Thanks for your quick response! So I should pass the auth token from OAuth as the single param to a new YouTube object, as if it was the API key? Something like this? 

`      const youtube = new YouTube(accessToken);
      var options = {
        forMine: true,
        order: 'date',
        type: 'video'
      };
      youtube.searchVideos('Centuries', 25, options)
      .then(results => {
        console.log(`I got ${JSON.stringify(results)} videos`);
      })
      .catch(console.error);`

**Comment by markm** [comment]
Thanks so much!
