### ISSUE TITLE
 YouTube Compliance Issues & Help

### ISSUE THREAD

**Issue by dylanjamesdev** [HyperCoder2975/simple-youtube-api#62]
Hi there,
I got an email from YouTube stating that this is not in compliance with them due to the fact that we store data for 12 months. Can you please help me find the code so I can change it from 12 months to 30 days? The report is pasted below. I have 15 days to fix the issue or they wont lift the IP ban.

July 27, 2020
ToS Violations Report V.1 YouTube API Services-Developer Policies
Violations that require immediate resolution:
E. Handling YouTube Data and Content (l​ ink​)
Policy #​: III.E.4.a-g​ (Refreshing, Storing, and Displaying API Data) (​link​)
● Violation: ​API Client is storing data for more than 30 days.
Proposed Solution: ​Regarding data storage, we only allow the API Clients to store the public data temporarily, but not more than 30 days and the stored data must either be refreshed or deleted after 30 days

**Comment by tjrgg** [comment]
This isn't an issue with this library. The library doesn't store data, it's only a wrapper for the YouTube Data API to retrieve data. It doesn't control what happens with the data after that.
